### ISSUE TITLE
書いてみる

### ISSUE THREAD

**Issue by delightech** [shinjukujohnny/make_dev_env#10]
# 概要

# やること

# FYI
* 親チケット

👍 
```ruby
def abc
  puts "test"
end
```

**Comment by shinjukujohnny** [comment]
![bluebird_robot_bot](https://user-images.githubusercontent.com/802953/52046402-fdc7fc80-2589-11e9-8541-207794e39a26.png)

**Comment by delightech** [comment]
# タスクリスト
- [x] aaa
- [x] bbb
- [ ] ccc

**Comment by delightech** [comment]
#9 
`print("test")`

> aaaaa

- [ ] test
